### ISSUE TITLE
Using G29 shifter

### ISSUE THREAD

**Issue by hgreen1** [functionreturnfunction/G27_Pedals_and_Shifter#20]
I have a slight issue using this guide with a Driving force shifter. (the one without the buttons). Whenever I press down on the shifter to go into reverse, buttons 8 through 24 activate. What would you recommend to remedy this? I've been trying to debug it, but since its the first time I've used the Arduino software, I don't quite know where to look.

**Comment by functionreturnfunction** [comment]
G27 uses something like a shift register and button matrix to read the states of multiple buttons over just a few wires. Since G29 has only one button (reverse) besides the x and y axis I'd imagine it's wired like a plain Jane momentary switch. Luckily it seems to be triggering on one of the pins that were used by the spi in the G27's connector, so it should be possible to get it working in code rather than changing the physical connections.

You'd need to strip out all the code dealing with the non-x/y pins from the shifter, and just read whatever pin the reverse button reads on in the same function that the gear is determined.  You can figure out what pinout that is by checking four continuity between the various pins and ground with and without the shifter pressed down.

**Comment by hgreen1** [comment]
I actually made a simple modification to the code, commenting out the for loop that activates all the buttons when using a G29/920 shifter.

```
void setButtonStates(int buttons[], int gear) {
  // release virtual buttons for all gears
...
  for (byte i = BUTTON_RED_CENTERRIGHT; i <= BUTTON_DPAD_TOP; ++i) {
    // Comment out the line below to use a Driving Force Shifter (The one without the buttons)
    // G27.setButton(buttonTable[i], buttons[i]);
  }
}
```

I just forgot to post the solution and close it.
